# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Sivas Sprinboot Maven Package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        ##server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        ##settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
        
    - name: Ping JFrog CLI
      run: jf rt ping

    - name: Setup Maven Config
      ##env:
        ##SERVER_ID: tal-eplus-saas
      run: |
        ##echo "::set-env name=repository::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        ##jf mvnc --server-id-resolve=$SERVER_ID --server-id-deploy=$SERVER_ID --repo-resolve-releases=auto-cli-virtual-$repository --repo-resolve-snapshots=auto-cli-virtual-$repository --repo-deploy-releases=auto-cli-virtual-$repository --repo-deploy-snapshots=auto-cli-virtual-$repository
        jf mvnc --repo-resolve-releases sampleapi-mvn-dev --repo-resolve-snapshots sampleapi-mvn-dev --repo-deploy-releases sampleapi-mvn-dev --repo-deploy-snapshots sampleapi-mvn-dev
     
    - name: Build & Deploy
      run: | 
        jf mvn clean install
        
    - name: Publish Build Information
      run: |
        # Collect environment variables for the build
        jf rt bce
        # Collect VCS details from git and add them to the build
        jf rt bag
        # Publish build info
        jf rt bp       
